### ISSUE TITLE
Handle errors when websocket fails to connect?

### ISSUE THREAD

**Issue by LRonHubs** [krystianity/node-bitstamp#2]
How do i find /callback errors when the websocket doesnt connect?

**Comment by krystianity** [comment]
Hi @LRonHubs sadly the guys from bitstamp decided to go for pusher. Pusher-js error handling is saddening. However.. in terms of errors and disconnects you will have to trust "pusher-js" automatic re-connect logic.

Additionally I have added 2 new events to the streams .on("connected") and .on("disconnected") that might help.

Furthermore, if you are having trouble with connecting you might want to checkout https://github.com/pusher/pusher-js for other DEBUG options.
