### ISSUE TITLE
Crypto Transactions method not implemented

### ISSUE THREAD

**Issue by mikhailjan** [krystianity/node-bitstamp#38]
I noticed that the Crypto Transactions (https://www.bitstamp.net/api/v2/crypto-transactions/) method hasn't been implemented by this library.

Can it be added please?

**Comment by krystianity** [comment]
should be added with #39 soon

**Comment by krystianity** [comment]
released with 3.1.0

**Comment by mikhailjan** [comment]
Thank you!
